---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[cim_bug_repro::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
